# Generated by Django 3.0.8 on 2020-07-05 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechanac', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('comentario', models.CharField(default='-', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tipoProduc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('t_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_cliente', to='asesoria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='productoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='asesoria.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='asesoria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('d_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_cliente', to='asesoria.cliente')),
            ],
        ),
    ]
